name: Test and coverage

on: [push, pull_request]

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Generate coverage report
        run: |
          go test -coverpkg=./... -coverprofile coverProfile.out ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: 068cea3c-e0ef-42e2-ba69-08f9ea8b264a
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella