name: Worfkflow

on:
  push:
    branches: [ main, develop ]
    tags: 
      - '**'
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: anjulapaulus/go-rocksdb:go1.16.15-rocks7.0.2
    steps:
      - name: Run coverage
        run: go test -coverpkg=./... -coverprofile coverage.txt ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
